cc_library(
    name = "parser",
    srcs = [
        "parser.c",
    ],
    hdrs = [
        "parser.h",
    ],
    deps = [
        "//io/ioutil",
        "//subc/token",
        "//subc/ast",
        "//subc/scanner",
    ],
    visibility = ["//visibility:public"],
)
