cc_library(
    name = "ast",
    srcs = [
        "ast.c",
    ],
    hdrs = [
        "ast.h",
    ],
    deps = [
        "//bling/token",
        "//bytes",
        "//utils",
    ],
    visibility = ["//visibility:public"],
)
