cc_binary(
    name = "blingc",
    srcs = [
        "main.c",
    ],
    deps = [
        "//bytes",
        "//bling/parser",
        "//bling/types",
        "//os",
        "//subc/cparser",
        "//subc/cemitter",
    ],
)
