cc_binary(
    name = "blingc",
    srcs = [
        "main.c",
    ],
    deps = [
        "//bling/parser",
        "//bling/types",
        "//os",
        "//path",
        "//subc/parser",
        "//subc/emitter",
    ],
)
