cc_library(
    name = "bytes",
    srcs = [
        "bytes.c",
    ],
    hdrs = [
        "bytes.h",
    ],
    deps = [
        "//errors",
        "//utils",
    ],
    visibility = ["//visibility:public"],
)
