cc_library(
    name = "path",
    srcs = [
        "path.h",
        "path.c",
    ],
    hdrs = [
        "path.h",
    ],
    deps = [
        "//builtin",
    ],
    visibility = ["//visibility:public"],
)
