cc_library(
    name = "parser",
    srcs = [
        "parser.c",
        "parser.h",
    ],
    hdrs = [
        "parser.h",
    ],
    deps = [
        "//bling/ast",
        "//bling/scanner",
        "//bling/token",
        "//bytes",
        "//fmt",
        "//io/ioutil",
        "//path",
    ],
    visibility = ["//visibility:public"],
)
