cc_library(
    name = "emitter",
    srcs = [
        "emitter.c",
    ],
    hdrs = [
        "emitter.h",
    ],
    deps = [
        "//bling/ast",
        "//bytes",
    ],
    visibility = ["//visibility:public"],
)
