cc_library(
    name = "bootstrap",
    srcs = [
        "bootstrap.c",
    ],
    deps = [
        "//builtin"
    ],
    defines = [
        "BOOTSTRAP",
    ],
    visibility = ["//visibility:public"],
)
