cc_library(
    name = "bootstrap",
    srcs = [
        "bootstrap.c",
    ],
    hdrs = [
        "bootstrap.h",
        "libc.h",
    ],
    defines = [
        "BOOTSTRAP",
    ],
    visibility = ["//visibility:public"],
)
