cc_library(
    name = "sys",
    srcs = [
        "fmt.c",
        "sys.c",
    ],
    hdrs = [
        "sys.h",
    ],
    deps = [
        "//bootstrap",
    ],
    visibility = ["//visibility:public"],
)
