cc_library(
    name = "scanner",
    srcs = [
        "scanner.c",
    ],
    hdrs = [
        "scanner.h",
    ],
    deps = [
        "//subc/ast",
        "//subc/token",
    ],
    visibility = ["//visibility:public"],
)
