cc_library(
    name = "runtime",
    srcs = [
        "clib.h",
        "desc.c",
        "map.c",
        "runtime.h",
        "slice.c",
        "types.c",
    ],
    hdrs = [
        "clib.h",
        "runtime.h",
    ],
    visibility = ["//visibility:public"],
)
