cc_library(
    name = "runtime",
    srcs = [
        "clib.h",
        "runtime.h",
        "slice.c",
    ],
    hdrs = [
        "clib.h",
        "runtime.h",
    ],
    visibility = ["//visibility:public"],
)
