cc_library(
    name = "cparser",
    srcs = [
        "cparser.c",
    ],
    hdrs = [
        "cparser.h",
    ],
    deps = [
        "//bling/token",
        "//bling/ast",
        "//bling/scanner",
        "//bling/parser",
        "//io/ioutil",
        "//slice",
    ],
    visibility = ["//visibility:public"],
)
