cc_library(
    name = "strings",
    srcs = [
        "strings.c",
    ],
    hdrs = [
        "strings.h",
    ],
    deps = [
        "//bytes",
        "//errors",
    ],
    visibility = ["//visibility:public"],
)
