cc_library(
    name = "os",
    srcs = [
        "os.c",
    ],
    hdrs = [
        "os.h",
    ],
    deps = [
        "//path",
        "//slice",
    ],
    visibility = ["//visibility:public"],
)
