cc_library(
    name = "os",
    srcs = [
        "os.c",
    ],
    hdrs = [
        "os.h",
    ],
    deps = [
        "//errors",
        "//paths",
        "//slice",
    ],
    visibility = ["//visibility:public"],
)
