cc_library(
    name = "cemitter",
    srcs = [
        "cemitter.c",
    ],
    hdrs = [
        "cemitter.h",
    ],
    deps = [
        "//bling/ast",
        "//bling/emitter",
        "//bling/types",
    ],
    visibility = ["//visibility:public"],
)
