cc_library(
    name = "emitter",
    srcs = [
        "emit.c",
    ],
    hdrs = [
        "emit.h",
    ],
    deps = [
        "//bling/ast",
        "//bling/emitter",
    ],
    visibility = ["//visibility:public"],
)
