cc_library(
    name = "ioutil",
    srcs = [
        "ioutil.c",
    ],
    hdrs = [
        "ioutil.h",
    ],
    deps = [
        "//bytes",
        "//os",
    ],
    visibility = ["//visibility:public"],
)
