cc_library(
    name = "types",
    srcs = [
        "types.c",
    ],
    hdrs = [
        "types.h",
    ],
    deps = [
        "//bling/ast",
        "//bling/emitter",
        "//bling/parser",
    ],
    visibility = ["//visibility:public"],
)
