cc_library(
    name = "errors",
    srcs = [
        "errors.c",
    ],
    hdrs = [
        "errors.h",
    ],
    deps = [
        "//bootstrap",
    ],
    visibility = ["//visibility:public"],
)
