cc_library(
    name = "utils",
    srcs = [
        "error.c",
        "map.c",
        "slice.c",
    ],
    hdrs = [
        "utils.h",
    ],
    deps = [
        "//bootstrap",
    ],
    visibility = ["//visibility:public"],
)
