cc_library(
    name = "builtin",
    srcs = [
        "builtin.c",
    ],
    hdrs = [
        "builtin.h",
    ],
    deps = [
        "//runtime"
    ],
    visibility = ["//visibility:public"],
)
