cc_library(
    name = "scanner",
    srcs = [
        "scanner.c",
    ],
    hdrs = [
        "scanner.h",
    ],
    deps = [
        "//bling/token",
        "//bytes",
    ],
    visibility = ["//visibility:public"],
)
