cc_library(
    name = "map",
    srcs = [
        "desc.c",
        "map.c",
        "types.c",
    ],
    hdrs = [
        "map.h",
    ],
    deps = [
        "//slice",
    ],
    visibility = ["//visibility:public"],
)
