cc_library(
    name = "walk",
    srcs = [
        "walk.c",
    ],
    hdrs = [
        "walk.h",
    ],
    deps = [
        "//bling/ast",
        "//bling/emitter",
    ],
    visibility = ["//visibility:public"],
)
