cc_library(
    name = "token",
    srcs = [
        "token.c",
    ],
    hdrs = [
        "token.h",
    ],
    deps = [
        "//bytes",
        "//sys",
        "//utils",
    ],
    visibility = ["//visibility:public"],
)
