cc_library(
    name = "token",
    srcs = [
        "token.c",
    ],
    hdrs = [
        "token.h",
    ],
    deps = [
        "//map",
        "//sys",
    ],
    visibility = ["//visibility:public"],
)
